import {
  copyResponseFileFx,
  downloadResponseFileFx,
  fetchResponseFileContentFx,
  fetchResponseFilesFx,
  removeResponseFileFx,
  updateResponseFileFx,
  uploadResponseFileFx,
} from './effects';
import {
  $files,
  $filesError,
  $hasMore,
  $isFilesLoading,
  $isLoadingMore,
  $page,
  $totalPages,
  fileDownloadRequested,
  fileRemoved,
  filesRequested,
  filesReset,
} from './stores';

export const mockResponseFileModel = {
  $files,
  $filesError,
  $isFilesLoading,
  $isLoadingMore,
  $hasMore,
  $page,
  $totalPages,
  filesRequested,
  filesReset,
  fileRemoved,
  fileDownloadRequested,
  fetchResponseFilesFx,
  fetchResponseFileContentFx,
  removeResponseFileFx,
  downloadResponseFileFx,
  updateResponseFileFx,
  uploadResponseFileFx,
  copyResponseFileFx,
};

export type {
  CopyResponseFileParams,
  DownloadResponseFileParams,
  FetchResponseFileContentParams,
  FetchResponseFilesParams,
  MockResponseFileMetaDto,
  RemoveResponseFileParams,
  ResponseFileContent,
  UpdateResponseFileParams,
  UploadResponseFileParams,
} from './types';
