import {
  copyCatalogRuleFx,
  fetchCatalogRulesFx,
} from './catalog-effects';
import {
  $catalogFetchMode,
  $catalogHasMore,
  $catalogPage,
  $catalogRules,
  $catalogRulesError,
  $catalogTotal,
  $catalogTotalPages,
  $isCatalogLoadingMore,
  $isCatalogRulesLoading,
  catalogRuleCopyRequested,
  catalogRulesRequested,
  catalogRulesReset,
} from './catalog-stores';
import {
  createRuleFx,
  fetchRulesFx,
  removeRuleFx,
  reorderRulesFx,
  updateRuleFx,
} from './effects';
import {
  $fetchMode,
  $hasMore,
  $isLoadingMore,
  $isRulesLoading,
  $page,
  $rules,
  $rulesError,
  $total,
  $totalPages,
  ruleCreated,
  ruleRemoved,
  rulesRequested,
  rulesReset,
  rulesReordered,
  ruleUpdated,
} from './stores';

export const mockRuleModel = {
  $rules,
  $page,
  $totalPages,
  $total,
  $fetchMode,
  $rulesError,
  $isRulesLoading,
  $isLoadingMore,
  $hasMore,
  rulesRequested,
  ruleCreated,
  ruleUpdated,
  ruleRemoved,
  rulesReordered,
  rulesReset,
  fetchRulesFx,
  createRuleFx,
  updateRuleFx,
  removeRuleFx,
  reorderRulesFx,
  $catalogRules,
  $catalogPage,
  $catalogTotalPages,
  $catalogTotal,
  $catalogFetchMode,
  $catalogRulesError,
  $isCatalogRulesLoading,
  $isCatalogLoadingMore,
  $catalogHasMore,
  catalogRulesRequested,
  catalogRuleCopyRequested,
  catalogRulesReset,
  fetchCatalogRulesFx,
  copyCatalogRuleFx,
};

export type {
  CatalogMockRuleResponseDto,
  CopyCatalogRuleParams,
  FetchCatalogRulesMode,
  FetchCatalogRulesParams,
  MockRulesCatalogControllerFindAllCatalogMethod,
  MockRulesCatalogControllerFindAllCatalogParams,
  PaginatedCatalogMockRulesResponseDto,
} from './catalog-types';

export type {
  CreateMockRuleDto,
  CreateRuleParams,
  FetchRulesMode,
  FetchRulesParams,
  MockRuleResponseDto,
  MockRulesControllerFindAllMethod,
  MockRulesControllerFindAllParams,
  PaginatedMockRulesResponseDto,
  RemoveRuleParams,
  ReorderRulesParams,
  UpdateMockRuleDto,
  UpdateRuleParams,
} from './types';
